---
gits:
  ajcepeda:
    repo: 'https://github.com/ALJCepeda/aljcepeda'
    version: 'facebook'
    umask: '0644'
groups: [ 'admins', 'developers' ]
users:
  alfred:
    groups: [ 'admins', 'developers' ]
    gits: [ 'ajcepeda' ]
  chris:
    groups: [ 'developers' ]
