---
packages: [ 'openssh-server', 'samba', 'build-essential', 'chrpath', 'libssl-dev', 'libxft-dev', 'libfreetype6-dev', 'libfreetype6', 'libfontconfig1-dev', 'libfontconfig1' ]
gits:
  ajcepeda:
    repo: 'https://github.com/ALJCepeda/aljcepeda'
    version: 'facebook'
    init: 'npm install'
    creates: 'node_modules'
groups: [ 'admins', 'developers' ]
users:
  alfred:
    groups: [ 'admins', 'developers' ]
    gits: [ 'ajcepeda' ]
  chris:
    groups: [ 'developers' ]
