- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: clone ajcepeda
      git: repo=git@github.com:ALJCepeda/aljcepeda.git
        dest=/sources
        key_file=/root/.ssh/id_rsa
        accept_hostkey=true
