- hosts: all
  remote_user: root
  become: yes
  tasks:
  - name: Download NodeJS
    get_url: url=https://deb.nodesource.com/setup_8.x dest=./dist/nodejs_install.sh mode=644

  - name: Add NodeJS Repo
    shell: ./dist/nodejs_install.sh creates=/usr/bin/nodejs

  - name: Install NodeJS
    apt: name=nodejs state=latest update_cache=yes

  - name: Build Playbooks
    shell: node build.js
    args:
      creates: dist/main.yml
