- hosts: all
  become: yes
  tasks:
  - name: Create Dist Folder
    file: dest=dist state=directory

  - name: Download NodeJS
    get_url: url=https://deb.nodesource.com/setup_8.x dest=dist/nodejs_install.sh mode=544

  - name: Add NodeJS Repo
    shell: dist/nodejs_install.sh creates=dist/main.yml

  - name: Install NodeJS
    apt: name=nodejs state=latest update_cache=yes

  - name: Install Modules
    shell: npm install
    args:
      creates: dist/main.yml

  - name: Build Playbooks
    shell: node build.js
    args:
      creates: dist/main.yml
