- hosts: all
  remote_user: root
  become: yes
  tasks:
  - name: Download NodeJS
    get_url: url=https://deb.nodesource.com/setup_8.x dest=/ansible_files/nodejs_install.sh mode=744

  - name: Add NodeJS Repo
    shell: /ansible_files/nodejs_install.sh creates=/bin/node 

  - name: Install NodeJS
    apt: name=nodejs state=latest update_cache=yes
