- hosts: all
  remote_user: root
  become: yes
  tasks:
  {{#each users}}
    {{#if gits}}
      {{#each gits}}
    - name: Clone {{ this }} for {{ @../key }}
        {{#with (lookup ../../gits this) as |gitObj|}}
      git: repo={{ gitObj.repo }}
        accept_hostkey=true
        dest=/home/{{ @../key }}/repos/{{ ../this }}
          {{#if ../../../key_file}}
        key_file={{ ../../../key_file }}
          {{/if}}
          {{#if gitObj.version}}
        version={{ gitObj.version }}
          {{/if}}

    - name: Initialize {{ ../this }} ({{ @../key }})
      shell: {{ gitObj.init }} 
      args:
        chdir: /home/{{ @../key}}/repos/{{ ../this }}
        creates: {{ gitObj.creates }}
      register: {{ ../this }}{{ @../key }}
        {{/with}}
      {{/each}}

      {{#each gits}}
        {{#with (lookup ../../gits this) as |gitObj|}}
    - name: chown {{ @../key }}
      file: path=/home/{{ @../key }} owner={{@../key}} group={{@../key}} recurse=yes
      when: {{ ../this }}{{ @../key }}.changed
        {{/with}}
      {{/each}}
    {{/if}}
  {{/each}}
