- hosts: all
  remote_user: root
  become: yes
  tasks:
  {{#each users}}
    {{#if gits}}
      {{#each gits}}
    - name: Clone {{ this }} for {{ @../key }}
        {{#with (lookup ../../gits this) as |gitObj|}}
      git: repo={{ gitObj.repo }}
        accept_hostkey=true
        dest=/home/{{ @../key }}/repos/{{ ../this }}
          {{#if ../../../key_file}}
        key_file={{ ../../../key_file }}
          {{/if}}
          {{#if gitObj.version}}
        version={{ gitObj.version }}
          {{/if}}
        {{/with}}

    - name: Set permissions for {{ this }} ({{ @../key }})
      file: path=/home/{{ @../key }}/repos/{{ this }} owner={{@../key}} group={{@../key}} recurse=yes
      {{/each}}
    {{/if}}
  {{/each}}
